dhis2/d2-ui

src/header-bar/HeaderBar.component.js, src/header-bar/menu-ui.js
=> Fixed the duplicate apps menu in the header bar in app-management-app

examples/index.html, examples/sidebar/index.js, examples/sidebar/simple-sidebar.js, examples/siderbar.html, webpack.config.js
=> #38 sidebar example

src/forms/Validators.js, test/forms/Validators.test.js
For validation before updating the new password
=> Added isValidPassword validator

examples/button/index.js, examples/svg-icon/index.js, src/svg-icon/SvgIcon.js, src/svg-icon/__tests__/SvgIcon.spec.js
This pull request contains: 
- Support for d2-ui svg icons for d2-ui button component
- Sorting svg icons in alphabetical order 
- Added disabled and style properties to svg icons
- Added default colors to svg icons
=> Support d2-ui svg icons in d2-ui button component

examples/form-builder/index.js, src/form-fields/MultiToggle.js, src/form-fields/__tests__/CheckBox.component.spec.js, src/form-fields/__tests__/MultiToggle.component.spec.js
Fixed "this" binding in MultiToggle component.
Added tests for MultiToggle, Checkbox
Added example for MultiToggle
=> Fix MultiToggle component and add tests

src/forms/FormField.component.js, src/forms/__tests__/FormField.component.spec.js
=> Fix 'this' binding for FormField component

src/form-fields/TextField.js, src/form-fields/__tests__/TextField.component.spec.js
* Prefer arrow function to .bind(this)
* use value param instead of e.target.value
* Add unit tests
=> Prefer arrow function and add tests for TextField component

src/form-fields/__tests__/CheckBox.component.spec.js
=> Added test for CheckBox wrapper style override

examples/svg-icon/index.js, src/svg-icon/SvgIcon.js
Currently used by the dashboards-app
=> Add email icon to svg-icons

src/i18n/TranslationDialog.component.js, src/i18n/translationForm.actions.js
Used in the dashboards app to reflect the translation changes directly in the UI
=> Propagate translations on translation success

examples/select-field/index.js, src/expression-manager/ExpressionManager.js, src/expression-manager/ProgramOperandSelector.js, src/group-editor/GroupEditor.component.js, src/group-editor/GroupEditorWithOrdering.component.js
issue: https://jira.dhis2.org/browse/DHIS2-2625
- Changed the programOperandSelector to handle an array instead of a collection as it has always been. 
- Linting of GroupEditor and GroupEditorWithOrdering that was causing warnings.
=> changed the PTEA expression format to actually add an id an not name

examples/sidebar/index.js, src/sidebar/Sidebar.component.js
Allows the menu to be used together with React Router.
=> Add support for paths in Sidebar menu

src/period-picker/PeriodPicker.component.js
Bug fix in regard [this](https://github.com/dhis2/d2-ui/issues/189) issue:
I have noticed the problem. However I do not have enough knowledge about d2-ui code to understand why the **reset** (see diff code) I removed was there. 
Better anyone with more knowledge on d2-ui to check it.
@varl could you give a check on it, please?
=> d2-ui issue 189 bug fix for PeriodPicker

examples/index.html, examples/layout.html, examples/layout/index.js, src/form-fields/TextField.js, src/layout/SinglePanel.component.js, src/layout/TwoPanel.component.js, webpack.config.js
- The <main> tag in both components now gets its style by merging the base style with the mainStyle component property
- Added defaultProps and propTypes
- Added an example to see the different layout components in action
=> Custom styles on SinglePanel and TwoPanel component

src/app-header/utils/menu-sources.js
Should fix https://jira.dhis2.org/browse/DHIS2-2997
=> Fix broken help-link

packages/sharing/src/PermissionPicker.component.js
Changes requested by Lars.
- Change font weight in permission picker from 400 to 500
- Change text in data sharing field
=> Change font weight and text on permission picker

package.json
=> Use concurrency 1 for travis

packages/legend/src/index.js
Make colorbrewer object available for apps that uses this package. 
import { colorbrewer } from '@dhis2/d2-ui-legend'
=> Export colorbrewer

packages/file-menu/src/__tests__/FileMenu.spec.js
=> Fix broken tests for FileMenu component

src/forms/FormBuilder.component.js
Fixed formbuilder to always validate a disabled field as valid.
=> DHIS2-3737 v29 backport of disabled fields validation

packages/forms/src/FormBuilder.component.js
Fixed formbuilder to always validate a disabled field as valid.
=> DHIS2-3737 disabled fields validation

src/forms/FormBuilder.component.js
Fixed formbuilder to always validate a disabled field as valid.
=> DHIS2-3737 v28 backport of formbuilder validating disabled fields

packages/legend/src/index.js
The Maps app needs access to individual components defined in this package.
=> Allow more components to be imported from d2-ui-legend

packages/sharing-dialog/README.md
Instructions for sharing dialog install readme was wrong.
=> update sharing dialog readme with import instructions

packages/file-menu/src/DeleteMenuItem.js
Fixes DHIS2-4171.
- propagate API error in callbacks so the app using this component can receive and handle it
=> DHIS2-4171: propagate API error in callbacks

packages/interpretations/package.json, packages/interpretations/src/components/interpretations/CommentTextarea.js, packages/interpretations/src/components/interpretations/InterpretationDialog.js
Fixes DHIS2-3428.
- enable user mentioning engine in the interpretation panel, both create/edit interpretation dialog and comment (reply) textarea
=> Use MentionsWrapper in interpretations panel

packages/mentions-wrapper/src/MentionsWrapper.js, yarn.lock
Position cursor after focus by using setTimeout.
=> Position cursor after focus

packages/core/README.md
No Jira issue.
- Add basic readme info for d2-ui-core components
=> Add basic usage info for d2-ui-core components

docs/RELEASING.md
=> Add troubleshooting info when only partial publish success

packages/rich-text/package.json
Fixes DHIS2-4079.
- remove unnecessary dependencies
=> Cleanup dependencies for d2-ui-rich-text

packages/file-menu/package.json, yarn.lock
Upgrade d2-ui-file-menu dependencies:
- MUI 3.0
- @dhis2/d2-ui-translation-dialog 2.0
- @dhis2/d2-ui-sharing-dialog 2.0
=> Upgrade file-menu to MUI 3.0, translation-dlg 2.0, sharing-dlg 2.0

packages/favorites-dialog/package.json, yarn.lock
Upgrade favorites dialog to the lates Material-UI and Sharing-Dialog versions.
=> Upgrade favorites dialog deps

packages/file-menu/src/RenameDialog.js, packages/file-menu/src/__tests__/RenameMenuItem.spec.js
Fixes DHIS2-4482.
- pass changed name/description to the onRename callback
=> DHIS2-4482: pass changed name/description to onRename callback

examples/create-react-app/src/components/period-selector-dialog.js, packages/period-selector-dialog/css/PeriodSelector.css, packages/period-selector-dialog/src/PeriodSelector.js, packages/period-selector-dialog/src/PeriodSelectorDialog.js, packages/period-selector-dialog/src/PeriodsList.js
Relates to DHIS2-3290
- Return selected periods on `hide button` click
- Provide list height property for periods lists height
=> Return periods on hide button click

examples/create-react-app/src/App.js, examples/create-react-app/src/components/org-unit-selector.js, packages/org-unit-dialog/i18n/en.pot, packages/org-unit-dialog/readme.md, packages/org-unit-dialog/src/OrgUnitDialog.js, packages/org-unit-dialog/src/OrgUnitSelector.js, packages/org-unit-dialog/src/index.js, yarn.lock
- Extract org units selection into separate component
=> Extract selector logic into separate component

packages/org-unit-dialog/src/index.js
- Export static user org units
=> Export user org units from org-unit-dialog component

packages/period-selector-dialog/src/PeriodListItem.js
=> Use import syntax in period-selector-dialog that allows treeshaking

examples/create-react-app/package.json, lerna.json, package.json, packages/favorites-dialog/package.json, packages/favorites-menu/package.json, packages/file-menu/package.json, packages/group-editor/package.json, packages/header-bar/package.json, packages/header-bar/src/HeaderBar.js, packages/header-bar/src/__tests__/HeaderBar.spec.js, packages/header-bar/src/header-bar-styles.js, packages/header-bar/src/menus/HeaderMenu.js, packages/header-bar/src/menus/ProfileMenu.js, packages/header-bar/src/notifications/NotificationItem.js, packages/header-bar/src/notifications/Notifications.js, packages/header-bar/src/search/SearchField.js, packages/header-bar/src/search/SearchResults.js, packages/icon-picker/package.json, packages/interpretations/package.json, packages/legend/package.json, packages/mentions-wrapper/package.json, packages/org-unit-dialog/package.json, packages/org-unit-select/package.json, packages/org-unit-tree/package.json, packages/sharing-dialog/package.json, packages/table/package.json, packages/translation-dialog/package.json, yarn.lock
- moves all MUI>1 versions to 3.3.1
- moves all MUI icons to 3.0.1
- moves lerna version to dependent version scheme
- consolidates MUI <1 to 0.20.0 release
=> chore: use a single mui version, upgrade header-bar

package.json, yarn.lock
- this updates `packages` to use symlinks instead of npm/yarn links
- updates the lock-file as well
=> Update build tools deps

package.json, yarn.lock
- reverts the carpet bombed yarn.lock
- re-applies the dep change
=> Avoid carpet bombing yarnlock

examples/create-react-app/src/components/org-unit-dialog.js, packages/org-unit-dialog/src/OrgUnitDialog.js, packages/org-unit-dialog/src/OrgUnitSelector.js, packages/org-unit-dialog/src/styles/OrgUnitDialog.style.js, packages/org-unit-tree/src/OrgUnitTree.component.js
Fixes DHIS2-4450.
- Use material-ui checkbox
=> Use material ui checkbox in org unit tree

yarn.lock
=> Remove d2@^31.1.1 from yarn lock

packages/core/src/theme/mui3.theme.js
PaperWidthLG is missing Width,
add width to Large dialogs as well
=> fix/ add width to large dialogs

packages/period-selector-dialog/css/PeriodSelector.css, packages/period-selector-dialog/src/Periods.js
- Adjusted styles to be more aligned with designs
- Border radius is enabled only on buttons' edges
- Removed space between buttons
=> Fix styles for period type buttons

packages/interpretations/src/components/interpretations/InterpretationDialog.js
Fixes DHIS2-5906.
- fix handling of user select for mentions
The same onChange callback cannot really be used, as the arguments passed are different.
=> DHIS2-5906: fix handling of user select for mentions

packages/mentions-wrapper/src/MentionsWrapper.js, packages/mentions-wrapper/src/__tests__/MentionsWrapper.spec.js
Related DHIS2-5906.
- Remove unnecessary API calls to fetch users list
When navigating with up/down arrows unnecessary API requests were fired.
Added tests.
=> Remove unnecessary API calls to fetch users list

packages/interpretations/src/components/Comment/NewCommentField.js, packages/interpretations/src/components/Interpretation/NewInterpretationField.js
Similar to Commit [#378](https://github.com/dhis2/d2-ui/commit/4c300043ef36971edb468c29845054a86ad32b15)
=> interpretations: pass onUserSelect instead of onInputchange to MentionsWrapper

packages/interpretations/src/components/Lists/InterpretationsList.js
Fix rendering Show / Hide more interpretations
=> Interpretations: fix show / hide more interpretations

README.md
Related to: https://github.com/dhis2/cli-packages/issues/12
Just documenting @varl's response from slack on how you'd link individual components locally when developing.
=> Add instructions on linking

packages/legend/src/ColorPicker.component.js
Ref: https://jira.dhis2.org/browse/DHIS2-5861
=> DHIS2-5861 - port bugfix from v29 to master

packages/legend/src/ColorPicker.component.js
Ref: https://jira.dhis2.org/browse/DHIS2-5861
=> DHIS2-5861 - port bugfix from v29 to v30

src/legend/Legend.component.js, src/legend/LegendItem.store.js
See https://github.com/dhis2/d2-ui/pull/401
=> DHIS2-6207/fix legend bug patch v29

packages/legend/src/Legend.component.js, packages/legend/src/LegendItem.store.js
See https://github.com/dhis2/d2-ui/pull/401
=> DHIS2-6207/fix legend bug patch v30

packages/legend/src/Legend.component.js, packages/legend/src/LegendItem.store.js
See https://github.com/dhis2/d2-ui/pull/401
=> DHIS2-6207/fix legend bug patch master

packages/legend/src/ColorPicker.component.js
Fixes https://jira.dhis2.org/browse/DHIS2-6354 and addresses a point in https://jira.dhis2.org/browse/DHIS2-6365
=> Fix legend item sorting v30

packages/legend/src/LegendItems.component.js
Fixes https://jira.dhis2.org/browse/DHIS2-6354 and addresses a point in https://jira.dhis2.org/browse/DHIS2-6365
=> Fix legend item sorting master

src/legend/Legend.component.js
See: https://github.com/dhis2/d2-ui/pull/416
=> DHIS2-6353/fix cancel create legends v29

packages/legend/src/ColorPicker.component.js
See: https://github.com/dhis2/d2-ui/pull/416
=> DHIS2-6353/fix cancel create legends v30

packages/legend/src/LegendItems.component.js
See: https://github.com/dhis2/d2-ui/pull/416
=> DHIS2-6353/fix cancel create legends master

packages/period-selector-dialog/package.json, yarn.lock
The upgrade includes a fix for when dragging items to the 2nd-to-last position in the list
=> chore: upgrade d2-ui-analytics for some fixes to item selector in period-selector

packages/period-selector-dialog/package.json, yarn.lock
Changes in Period Selector include:
- multidrag items in selected list
- visual tweaks for some scrollbar issues
=> fix: visual tweaks in ItemSelector in Period selector

packages/period-selector-dialog/package.json, yarn.lock
=> fix: get latest item selector with active button styles for period-selector

packages/file-menu/src/GetLinkDialog.js
Fixes DHIS2-6338.
- fix the URL used in the FileMenu Get Link dialog for opening a chart AO in the new DV app
=> fix(file-menu): fix URL for opening AO in DV (DHIS2-6338)

packages/period-selector-dialog/package.json, yarn.lock
Includes all the latest updates for ItemSelector
=> chore: upgrade item selector to v1 for period selector

packages/period-selector-dialog/src/PeriodSelector.js, packages/period-selector-dialog/src/modules/FixedPeriodsGenerator.js, packages/period-selector-dialog/src/modules/RelativePeriodsGenerator.js, packages/period-selector-dialog/src/modules/__tests__/FixedPeriodsGenerator.spec.js
Fixes DHIS2-2971.
- implement bi-weekly periods in shared period selector component used in new analytics apps
- added tests for all the supported fixed periods, this required to change `new Date()` to `new Date(Date.now())` to be able to mock Date.now() and get consistent test results over time.
=> chore: Bi weekly periods (DHIS2-2971)

packages/period-selector-dialog/src/modules/FixedPeriodsGenerator.js, packages/period-selector-dialog/src/modules/__tests__/FixedPeriodsGenerator.spec.js
Fixes DHIS2-2971.
- fix week and bi-week calculations based on ISO week numbering
=> fix(period-selector): fix weekly biweekly calculation

packages/period-selector-dialog/package.json, packages/period-selector-dialog/src/PeriodSelector.js, yarn.lock
- @dhis2/d2-ui-analytics has been renamed to @dhis2/analytics; update the dependency.
=> fix: update @dhis2/analytics dep

packages/file-menu/src/__tests__/DeleteMenuItem.spec.js
Fixes DHIS2-4171.
- test that the error callback receives arguments
=> chore: add test for error callback args (DHIS2-4171)

packages/interpretations/package.json, packages/period-selector-dialog/src/styles/PeriodFilter.style.js
Fixes DHIS2-7609.
- avoid wrapping the period type label on multiple lines
- cleanup unused styles
=> fix: avoid wrapping period type label on multiple lines

package.json
Fixes DHIS2-7609.
- need a new version and npm package in DV with the fix
=> fix: upgrade dhis2/d2-ui to v6.3.1

package.json, packages/period-selector-dialog/src/styles/PeriodFilter.style.js
Doh!
Fixes DHIS2-7609.
- fix typo in CSS rule
=> fix: typo in CSS rule v6.3.2

packages/file-menu/src/DeleteDialog.js, packages/file-menu/src/DeleteMenuItem.js, packages/file-menu/src/FileMenu.js, packages/file-menu/src/GetLinkDialog.js, packages/file-menu/src/GetLinkMenuItem.js, packages/file-menu/src/OpenMenuItem.js, packages/file-menu/src/RenameDialog.js, packages/file-menu/src/RenameMenuItem.js, packages/file-menu/src/SaveAsDialog.js, packages/file-menu/src/SaveAsMenuItem.js, packages/file-menu/src/SaveMenuItem.js, packages/file-menu/src/ShareMenuItem.js, packages/file-menu/src/WriteInterpretationDialog.js, packages/file-menu/src/WriteInterpretationMenuItem.js
Fixes DHIS2-7728.
- fix validation for `fileType` prop to support `visualization` as value
(The fix commit is what is relevant)
=> fix: add support for visualization api

package.json, packages/file-menu/src/DeleteDialog.js, packages/file-menu/src/DeleteMenuItem.js, packages/file-menu/src/FileMenu.js, packages/file-menu/src/GetLinkDialog.js, packages/file-menu/src/GetLinkMenuItem.js, packages/file-menu/src/OpenMenuItem.js, packages/file-menu/src/RenameDialog.js, packages/file-menu/src/RenameMenuItem.js, packages/file-menu/src/SaveAsDialog.js, packages/file-menu/src/SaveAsMenuItem.js, packages/file-menu/src/SaveMenuItem.js, packages/file-menu/src/ShareMenuItem.js, packages/file-menu/src/WriteInterpretationDialog.js, packages/file-menu/src/WriteInterpretationMenuItem.js, packages/file-menu/src/util.js
Fixes DHIS2-7728.
- version bump
=> fix: update version to 6.3.3

package.json
Fixes DHIS2-7335, DHIS2-8118.
- publish new version
=> chore: v6.4.0

package.json, packages/favorites-dialog/i18n/en.pot, packages/favorites-dialog/src/EnhancedToolbar.js
Add space between the different filter selects.
Align icons and text in vis type filter.
Fixes DHIS2-8263.
- small style fixes related to the filters in FavoritesDialog
=> fix: remove filter tooltip, adjust style for filters/icons

package.json
Upgrades analytics library in period-selector-dialog
=> chore(deps): bump @dhis2/analytics from 6.5.5 to 6.5.6

package.json
Related to https://jira.dhis2.org/browse/DHIS2-8451.
For that ticket I forgot to release a new version to use in DV.
=> chore(release): cut v6.5.11

.tx/config
=> fix: favorites-dialog needs transifex config

package.json, packages/favorites-dialog/src/EnhancedToolbar.js, packages/interpretations/src/api/__tests__/users.spec.js, packages/interpretations/src/components/Interpretation/__tests__/Replies.spec.js
Pushing a few lint fixes, together with a version bump. (I should have done the version bump with the previous PR)
=> fix: patch version bump

package.json, packages/file-menu/i18n/en.pot, packages/file-menu/src/DeleteDialog.js
Part of fix for: https://jira.dhis2.org/browse/DHIS2-8638
=> fix: add missing i18n.t statements (DHIS2-8638)

package.json
Fixes [DHIS2-9217](https://jira.dhis2.org/browse/DHIS2-9217).
- new version 7.0.5 for the stacked area type in favorites-dialog component.
- forgot to push a new version. Pushing directly to master is not allowed.
=> fix: new version v7.0.5

examples/create-react-app/src/index.js, package.json, packages/interpretations/src/api/__tests__/helpers.spec.js, packages/interpretations/src/api/helpers.js, packages/interpretations/src/components/Avatar/UserAvatar.js, packages/interpretations/src/components/Avatar/WithAvatar.js, packages/interpretations/src/components/Avatar/__tests__/UserAvatar.spec.js, packages/interpretations/src/components/Cards/__tests__/InterpretationsCard.spec.js, packages/interpretations/src/components/Comment/Comment.js, packages/interpretations/src/components/Comment/NewCommentField.js, packages/interpretations/src/components/Interpretation/Interpretation.js, packages/interpretations/src/components/Interpretation/NewInterpretationField.js, packages/interpretations/src/components/Interpretation/__tests__/Interpretation.spec.js
`firstName` and `surname` are not returned from the API anymore.
Compute the initials for the avatar from `displayName` instead.
=> fix(interpretations): compute avatar initials from displayName

package.json, packages/interpretations/src/components/Buttons/ActionButton.js
New translations
Also, applied styling fixes to 1 file to trigger a semantic change.
=> fix: v7.0.9

.github/workflows/dhis2-verify-lib.yml, docs/RELEASING.md, scripts/publish-build.sh
=> ci: manual release action

packages/interpretations/i18n/en.pot, packages/interpretations/src/markdown/__tests__/formats.spec.js, packages/interpretations/src/markdown/formats.js
=> fix: missing translations in interpretations rich text [DHIS2-8638]

packages/interpretations/src/components/Buttons/ActionButton.js, packages/interpretations/src/components/Buttons/getIcons.js
=> fix: interpretations strings must be determined at runtime [DHIS2-8638]

packages/favorites-dialog/src/EnhancedToolbar.js, packages/favorites-dialog/src/actions/index.js
Fixes [DHIS2-10611](https://jira.dhis2.org/browse/DHIS2-10611).
- Fix debounce on search field to avoid hitting the backend too much while searching
=> fix(favorites-dialog): fix broken debounce on favorites search DHIS2-10611

package.json
=> chore: bump version to v7.1.5

docs/RELEASING.md, package.json
=> fix: v7.1.8

package.json, packages/sharing-dialog/src/Sharing.component.js
=> feat: release offline interpretations and sharing

package.json
Forgot to bump the version in PR https://github.com/dhis2/d2-ui/pull/700
=> chore: bump version to v7.3.1

examples/create-react-app/package.json, examples/create-react-app/src/components/interpretations.js, packages/interpretations/package.json, packages/interpretations/src/api/redirect.js, packages/interpretations/src/translations/modelNametranslator.js, yarn.lock
Fixes [DHIS2-11699](https://jira.dhis2.org/browse/DHIS2-11699)
- link the `visualization` prop to the `VISUALIZATION` type
- (BONUS) add visualization to the model name translation
=> fix: interpretations panel crash for visualizations (DHIS2-11699)

packages/interpretations/src/api/redirect.js, packages/interpretations/src/components/Buttons/RedirectButton.js
- add support for event visualizations
- fix URL for DV when using the View in app button
=> fix: add support for event visualizations
