dhis2/d2-ui

- src/expression-manager/dataElementOperandSelector.actions.js
Because d2 now url encodes the query part of the url additional
uriencoding would result in double encoded entities
> Fix bug in data element operand search

- examples/data-table/index.js
- src/data-table/DataTableRow.component.js
- src/data-table/data-value/Color.component.js
- src/data-table/data-value/valueRenderers.js
- test/data-table/DataTableRow.component.test.js
- test/data-table/dataTableValueRenderers.test.js
Specifically related to the date bug (DHIS2-955)
Dates will now be displayed using the Intl.dateFormat (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
When this is not available we'll parse the string and display it.
Additionally the rework makes adding custom renderers for values easier.
The old solution required modification of the Row component to be able
to displayer other values. With the new solution addValueRenderer can be used.
> Rework value rendering in DataTable

- src/sharing/SharingDialog.component.js
- test/sharing/SharingDialog.component.test.js
Fixes a bug where the Sharing dialog would load with an invalid id- and type combination when navigating between categories in the maintenance app. Attempting to fetch the shared object only when the dialog is open fixes this problem.
> feature/sharing-dialog: Load shared object only when the dialog is open.

- src/i18n/LocaleSelector.component.js
- src/i18n/TranslationForm.component.js
- src/i18n/__tests__/LocaleSelector.component.spec.js
Changing from React.createClass to class x extends Component means that the component (non-lifecycle) methods need to explicitly bind 'this'.
There were no unit tests for for this component. Unit tests are now added and they would catch the error that has been fixed in this commit.
> Fix broken LocaleSelector component and add tests

- examples/text-field/index.js
- src/text-field/TextField.js
- src/text-field/__tests__/TextField.spec.js
Also adds properties to support hint text and fullwidth. Note that the props passed in to the d2-ui component comply with the MUI 1.0 property naming. (multiline, placeholder)
I rearranged the properties alphabetically which makes the code changes appear bigger than they actually are. Apologies for that.
> Add new TextField properties to support multiline fields

- src/controlbar/ControlBar.js
- src/controlbar/__tests__/ControlBar.spec.js
- src/form-fields/CheckBox.component.js
- Fixed 1 broken test so that the build will succeed. To make sure no discrepancies will happen in the future I exported the height constant from the ControlBar component.
- CheckBox wrapper can now be styled via `props.wrapperStyle`. These styles will be merged with the existing styles to ensure backwards compatibility.
- I also rewrote the CheckBox as a functional component and declared some more propTypes and defaultProps to keep the linter happy.
> Allow CheckBox wrapper to be styled and fix broken test

- src/text-field/TextField.js
Text wrapped floating label texts overlaps the inputfield, and this style fix only allows single line labels.
> Don't wrap floating label texts

- src/data-table/DataTableContextMenu.component.js
- Changes execution order so that the popup is hidden first, and the action is run afterwards
- Removes timeout from code because there was no obvious need for it and it would break sequence changes
- This fix solves problems with navigating away via the contextMenu and destroying the current view in the process
> Hide first and then run action

- examples/org-unit-tree/index.js
- src/org-unit-tree/OrgUnitTree.component.js
Alternative suggestion for filtering the tree using path instead of id. By using this approach the parents of deeply nested children will always be displayed in the tree.
Another additional example, is that it now uses the same structure as the initiallyExpanded property. Which means you can easily expand the filtered tree too.
> Filter by path instead of ID

- examples/form-builder/index.js
- src/form-fields/DropDown.component.js
- src/form-fields/TextField.js
- DropDown now handles emptyOptions properly
- TextField can have type="search" and Safari will render correctly
- Updated examples to reflect both changes
> Fixes on TextField and DropDown:

- src/form-fields/DropDown.component.js
- selectionRenderer function was causing problems in maintenance app so removed that
- Instead the empty items gets " " as a label which will still prevent anything from showing over the hintText
> Alternative way to display emptyOption

- examples/sidebar/index.js
- src/sidebar/Sidebar.component.js
Sidebar improvement in regard the previous addition of path. I have noticed it would be more flexible if we have the possibility to define the container element. It will make it easier to integrate with React Router for example.
@varl review it and merge please.
> Sidebar with container element

- packages/core/package.json
- packages/favorites-dialog/package.json
- packages/favorites-menu/package.json
- packages/formula-editor/package.json
- packages/group-editor/package.json
- packages/header-bar/package.json
- packages/icon-picker/package.json
- packages/legend/package.json
- packages/org-unit-select/package.json
- packages/org-unit-tree/package.json
- packages/sharing-dialog/package.json
- packages/table/package.json
- packages/translation-dialog/package.json
- Use semantic-release notation for commits
- add org scope (dhis2) to packages so we can deal with updates on a scope basis (`yarn upgrade --scope=dhis2`)
- update versions (copypaste mangled)
- update descriptions (copypaste mangled)
> Scope packages for dhis2

- packages/header-bar/src/search/SearchField.js
- fix warning
_index.js:2178 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail._
- *material-ui* _TextField_ does not support _ref_ references
- move search box reference to parent div
- fix naming in _focusSearchField_ func. _searchField_ is referring to _searchBox_ then trying to find _searchField_
> refactor search field reference

- packages/translation-dialog/src/LocaleSelector.component.js
- packages/translation-dialog/src/__tests__/LocaleSelector.component.spec.js
This is a bit strange that it started to fail now. I've checked the React code and they don't create the instance property `state` until the component either:
* sets it manually in the constructor
* calls `setState`
The component test is set up to expect that `state` is an empty object after the component is created. The component does not set `state` in the constructor so the test is incorrect.
- Change the expected value from `{}` to `null`
> LocaleSelector component test assumes state is an empty object, but no state is created in constructor

- packages/favorites-dialog/src/EnhancedTable.js
Before: 2018-41-04, after: 2018-05-04
Using a date formatting library is probably a good idea...
Fixes TECH-52.
- Bug fix. The formatting of the dates shown in the dialog was broken
> Fix bug in date formatting

- packages/favorites-dialog/src/Favorites.js
"Favorites" cannot be used as it now a confusing term.
A title is not really needed for the dialog. Removed all together.
- Remove title in Favorites dialog
> Remove Favorites dialog title

- packages/file-menu/src/FileMenu.js
- packages/file-menu/src/SaveAsDialog.js
- packages/file-menu/src/SaveMenuItem.js
- packages/file-menu/src/__tests__/FileMenu.spec.js
- packages/file-menu/src/__tests__/SaveMenuItem.spec.js
- show the dialog for requesting name/description when saving a new analytics object and use the SaveAs callback (POST request)
- if an existing analytics object is available, use the Save callback (PUT request)
> Fix FileMenu/Save when dealing with a new analytics object

- packages/file-menu/src/FileMenu.js
- packages/file-menu/src/__tests__/FileMenu.spec.js
- New button in the File menu should be always enabled
The reason is that when an app is launched without a specific analytic object loaded, it should be possible to discard all the unsaved changes and start from scratch.
The New button is also enabled when an existing analytics object is loaded, which allows for resetting the app and starting create a new object.
> Enable New button by default (DHIS2-3935)

- packages/interpretations/README.md
- packages/interpretations/i18n/en.pot
- packages/interpretations/package.json
- packages/interpretations/src/components/html-editor/CKEditor.js
- packages/interpretations/src/components/html-editor/RichEditor.js
- packages/interpretations/src/components/html-editor/__tests__/CKEditor.spec.js
- packages/interpretations/src/components/html-editor/__tests__/RichEditor.spec.js
- packages/interpretations/src/components/interpretations/CommentTextarea.js
- packages/interpretations/src/components/interpretations/Interpretation.js
- packages/interpretations/src/components/interpretations/InterpretationComments.js
- packages/interpretations/src/components/interpretations/InterpretationDialog.js
- packages/interpretations/src/components/interpretations/InterpretationsCard.js
- packages/interpretations/src/components/interpretations/InterpretationsStyles.js
- packages/interpretations/src/components/interpretations/__tests__/CommentTextarea.spec.js
- packages/interpretations/src/components/interpretations/__tests__/InterpretationComments.spec.js
- packages/interpretations/src/components/interpretations/__tests__/InterpretationDialog.spec.js
- packages/interpretations/src/components/interpretations/misc.js
- packages/interpretations/src/models/__tests__/helpers.spec.js
- packages/interpretations/src/models/__tests__/users.spec.js
- packages/interpretations/src/models/comment.js
- packages/interpretations/src/models/helpers.js
- packages/interpretations/src/models/users.js
- packages/interpretations/src/util/api.js
- yarn.lock
Fixes https://jira.dhis2.org/browse/DHIS2-3422
Requires https://github.com/dhis2/maps-app/pull/13
- Textarea for interpretation and interpretation comments use now CKEditor with link/emoji buttons.
- Rich editor supports mentioning (`@username`)
- It uses same markup than analytics east region, will be updated to new markup on next iteration.
> [interpretations] Ckeditor and mentions for interpretations and comments

- packages/file-menu/src/FileMenu.js
- packages/file-menu/src/__tests__/FileMenu.spec.js
- fix wrong prop type for fileId, it's String not Object
- add tests for the situation when fileId is passed as prop
> Fix FileMenu fileId proptype

- packages/sharing-dialog/src/PermissionOption.component.js
- packages/sharing-dialog/src/SharingDialog.component.js
- packages/sharing-dialog/src/__tests__/SharingDialog.component.spec.js
Fixes DHIS2-2151-Sharing-UI.
Add three new props for the new program access UI in the Maintenance app:
- doNotPost: used if the user wants to save the changes themselves. Makes the sharing dialog "lazy", so to say, compared to the elsewise "eager" instant POST-ing of changes.
- sharedObject: used if the user wants to supply their own object to share. Using this prop will skip the GET-request on sharing settings that is normally made by the sharing dialog.
- onConfirm: used to differentiate "cancelling" and "confirming" changes made in the dialog when using the "doNotPost" prop.
- Update tests to accomodate these changes.
> DHIS2-2151-Sharing-UI

- packages/sharing-dialog/src/SharingDialog.component.js
Fixes DHIS2-2151-Sharing-UI.
- Add margin between 'close' and 'apply' buttons in the sharing dialog.
> DHIS2-2151-Sharing-UI: Add margin between 'close' and 'apply'

- packages/interpretations/i18n/en.pot
- packages/interpretations/src/components/interpretations/Interpretation.js
- packages/interpretations/src/components/interpretations/InterpretationDialog.js
- packages/interpretations/src/components/interpretations/InterpretationsCard.js
- packages/interpretations/src/components/interpretations/__tests__/InterpretationDialog.spec.js
- packages/interpretations/src/components/interpretations/__tests__/InterpretationsCard.spec.js
- packages/interpretations/src/models/interpretation.js
Fixes DHIS2-3428
- On interpretation create: show action "Save & share". It saves the interpretation and then opens the sharing dialog of this new interpretation. Note that the interpretation starts with the same sharing the parent object has.
- On interpretation edit: action "Save" (and does not open sharing dialog)
- Add action "Share" to interpretation on detail.
> [interpretations] Use action Save&share on interpretation create and Share on existing

- packages/header-bar/src/header-bar-styles.js
Fixes: TECH-107 
- Added word-wrap: break-word to menuItem styles so long app names without spaces will also be broken into multiple lines instead of overflowing horizontally
> Prevents long app names without spaces from overflowing horizontally

- packages/interpretations/src/components/details/DetailsCard.js
- packages/interpretations/src/components/details/__tests__/DetailsCard.spec.js
- packages/interpretations/src/models/__tests__/helpers.spec.js
- packages/interpretations/src/models/helpers.js
Fixes DHIS2-3428.
- Was using object.description, should be object.displayDescription
> [interpretations] Use displayInterpretation on details card

- packages/interpretations/i18n/en.pot
- packages/interpretations/src/components/Interpretations.js
- packages/interpretations/src/components/details/DetailsCard.js
- packages/interpretations/src/components/details/DetailsCardStyles.js
- packages/interpretations/src/components/details/__tests__/DetailsCard.spec.js
- packages/interpretations/src/components/interpretations/InterpretationDialog.js
- packages/interpretations/src/models/__tests__/helpers.spec.js
- packages/interpretations/src/models/helpers.js
- packages/interpretations/src/util/i18n.js
https://jira.dhis2.org/browse/DHIS2-3428
- Add subscription icon button to details card.
- Note: Icons are the same type we have in d2a, but built-in material-ui icons use the "filled" theme, while in d2a we used "outlined". 
- Check screenshot to validate the position of the icon within the card.
> Add subscription icon to details card

- packages/interpretations/src/components/interpretations/InterpretationsStyles.js
- packages/interpretations/src/components/interpretations/__tests__/Interpretation.spec.js
- packages/interpretations/src/components/interpretations/misc.js
https://jira.dhis2.org/browse/DHIS2-3428
The 2.29 user page in messaging went away, and there is currently no public user page to link to (https://jira.dhis2.org/browse/DHIS2-691)
I've changed the text color to a grey one, blue suggests a link.
> [interpretations] Replace user link by a text span

- packages/translation-dialog/src/TranslationForm.component.js
Fixes DHIS2-4183
- The loader div and the form now have an equal min-height so that the dialog-content's dimensions are more accurate when the dialog opens and its position is computed
- Increased the min width value from 250 to 350 because the loaded form's normal height is around 360
- Added some padding above the buttons
> Make sure that dialog opens vertically centred

- packages/file-menu/src/GetLinkDialog.js
The link does not work at the moment, until the headless browser
solution for downloading maps is in place.
- Remove the open in API link for maps
> Remove API link for maps in FileMenu/GetLink dialog

- packages/file-menu/src/GetLinkDialog.js
Fixes DHIS2-4253.
- always use absolute URL for the links to an app.
This is to allow use of a copy pasted URL
> DHIS2-4253: always use absolute URL for copy paste

- examples/create-react-app/src/components/feedback-snackbar.js
- packages/core/src/feedback-snackbar/FeedbackSnackbar.component.js
Needed to allow a parent component to update its state when snackbar closes. This component is being used for the new Reports App.
> Adding onclose handler for feedback snackbar

- src/data-table/DataTable.component.js
- src/data-table/DataTableHeader.component.js
Related to adding an icon in Maintenance app, so that you can have an optional element in above the context-menu column. This will be a "settings icon" in maintenance.
> Add optional node to render in header for contextmenu

- examples/create-react-app/src/components/period-selector-dialog.js
- packages/period-selector-dialog/src/PeriodSelector.js
- packages/period-selector-dialog/src/PeriodSelectorDialog.js
- packages/period-selector-dialog/src/Periods.js
As title says enable support for initially selected periods.
Typical use case: periods selected in favorite/Analytic object.
> Enable support for initially selected periods in period-selector-component

- packages/org-unit-tree/src/OrgUnitTree.component.js
**UPDATE**: Please ignore this for now. It seems this fix just masks an underlying problem.
Fixes DHIS2-966
This doesn't fully fix DHIS2-966 but will do so partly. At least the UI is updated after an OrgUnit is moved
- Add a second `forceReload` parameter with value `true` to the call to `root.children.load`.
- By adding this parameter d2 will actually fetch new data, instead of just returning the existing collection. See the [relevant code in d2 here](https://github.com/dhis2/d2/blob/master/src/model/ModelCollectionProperty.js#L165-L167).
> Add forceReload parameter to children.load call so they are actually re-fetched

- examples/create-react-app/src/components/list-select.js
- examples/create-react-app/src/components/period-selector.js
- packages/org-unit-tree/src/OrgUnitTree.component.js
There were dozens of console errors along the lines of "duplicate key" and "onClick={false}" (screenshot below), so I quickly fixed them.  This reduces create-react-app example app console chattiness significantly.  The OrgUnitTree.js fix also applies outside the example app.
> Fix console errors in examples/create-react-app and OrgUnitTree

- examples/create-react-app/src/components/period-selector-dialog.js
- examples/create-react-app/src/components/period-selector.js
- packages/period-selector-dialog/css/PeriodSelector.css
- packages/period-selector-dialog/src/FixedPeriods.js
- packages/period-selector-dialog/src/OfferedPeriods.js
- packages/period-selector-dialog/src/PeriodListItem.js
- packages/period-selector-dialog/src/PeriodSelector.js
- packages/period-selector-dialog/src/PeriodSelectorDialog.js
- packages/period-selector-dialog/src/Periods.js
- packages/period-selector-dialog/src/PeriodsList.js
- packages/period-selector-dialog/src/RelativePeriods.js
- packages/period-selector-dialog/src/SelectedPeriods.js
- packages/period-selector-dialog/src/reducers/periods.js
- yarn.lock
This PR Includes:
- Removing prop onPeriodsSelect
- adding two new prop functions onSelect / onDeselect
onSelect: Passes period ranges to parent component when a period range is selected (fired on doubleclick or selecting items through arrowButton)
onDeselect: Passes period ranges to parent component when a period range is deselected (fired onClick on <RemoveItemButton /> for selected periods, and on deselect through arrowButton).
- Additional styling according to [design document](https://projects.invisionapp.com/d/main#/console/12702965/266159910/preview)  and Data Visualizer's Data Dimension is added.
- 1 Additional if-test on the reducer's toggling function which enables deToggling of already selected items
prop periods have been changed to selectedItems (reflecting Data Dimension …
> remove PeriodSelectorDialog's  onPeriodsSelect prop, replaced by onSelect / onDeselect

- packages/core/src/app/__tests__/D2UIApp.spec.js
- packages/org-unit-tree/src/OrgUnitTree.component.js
- packages/sharing-dialog/src/Sharing.component.js
- packages/sharing-dialog/src/__tests__/Sharing.component.spec.js
- packages/translation-dialog/src/TranslationForm.component.js
- packages/translation-dialog/src/translation.store.js
- packages/translation-dialog/src/translationForm.actions.js
When the package is flatpacked, the build directory will not exist.
In D2UIApp.spec.js I removed an import and some variables that are not used.
> task/remove "build" from import path of d2-ui-core components

- examples/create-react-app/src/App.js
- packages/core/src/theme/mui3.theme.js
- packages/favorites-dialog/src/Favorites.js
- packages/org-unit-dialog/src/OrgUnitDialog.js
- packages/period-selector-dialog/src/PeriodSelectorDialog.js
- packages/sharing-dialog/src/SharingDialog.component.js
- packages/translation-dialog/src/TranslationForm.component.js
Fixes DHIS2-5043.
- Override `DialogTitle > h6` component for consistent dialog title styling consistent with design spec
- Standardize the use of `variant="contained"` and `color="primary"` in various `d2-ui` dialog components.
- Remove several cases of custom `style={}` usage
- Use the DHIS2 Mui3 theme in the `d2-ui` create-react-app example.
> DHIS2-5043 - Standardize and clean up dialog styles.

- packages/favorites-dialog/src/EnhancedToolbar.js
This PR does two things within Favorites Dialog:
- Fix an issue in Internet Explorer which defaults to `flex-shrink: 1` (unlike chrome which defaults to `flex-shrink: 0` and so was compressing the Select field
- Make the ToolTip around the Filter select field a controlled input so we can hide it when the select menu is open - previously the tooltip would stick on top of the menu causing mouse input issues or flickering and would also never be properly dismissed.
*NB*: Also did a prettify pass, though the settings seem a bit weird in d2-ui...
> Fix IE flexbox bug and persistently-open tooltip in Favorites Dialog

- packages/file-menu/src/DeleteDialog.js
Fixes partly DHIS2-5257.
- Fix success callback handling for delete action
Only call it when the promise resolves.
> Fix success callback handling for delete action

- examples/create-react-app/src/components/org-unit-dialog.js
- examples/create-react-app/src/components/org-unit-select.js
- packages/interpretations/package.json
- packages/interpretations/src/components/CollapsibleCard.js
- packages/interpretations/src/components/details/DetailsCardStyles.js
- packages/interpretations/src/components/interpretations/CommentTextarea.js
- packages/interpretations/src/components/interpretations/InterpretationsCard.js
- packages/interpretations/src/components/interpretations/InterpretationsStyles.js
- yarn.lock
In particular:
* Increase padding around `No Interpretations` text
* Fix card action hover, padding, margins, etc. and consolidate them into one `div`
* Use non-raised Mui `Card` style since we don't use raised cards anywhere else
* Refactor some DOM elements to use more idiomatic styles
* Improve padding around comment avatars
Also remove Mui deprecation warning from the example app
Before:
After:
> Improve styling of Interpretations cards

- packages/file-menu/src/FileMenu.js
Tiny update to font-size in FileMenu button - use 15px not 16px
> Use 15px font-size for FileMenu button

- examples/create-react-app/src/components/file-menu.js
- packages/core/src/theme/mui3.theme.js
- packages/favorites-dialog/src/Favorites.js
- packages/favorites-dialog/src/FavoritesDialog.js
- packages/favorites-dialog/src/index.js
- packages/file-menu/src/DeleteDialog.js
- packages/file-menu/src/FileMenu.js
- packages/file-menu/src/GetLinkDialog.js
- packages/file-menu/src/OpenMenuItem.js
- packages/file-menu/src/RenameDialog.js
- packages/file-menu/src/SaveAsDialog.js
- packages/file-menu/src/SaveAsMenuItem.js
- packages/file-menu/src/TranslateMenuItem.js
- packages/period-selector-dialog/css/PeriodSelector.css
- packages/sharing-dialog/src/SharingDialog.component.js
- packages/translation-dialog/src/TranslationDialog.component.js
This PR is a dependency of, and related to Data Visualizer's: [Task/options dialog styling [DHIS2-5204] [DHIS2-5224] #136](https://github.com/dhis2/data-visualizer-app/pull/136).
In DV PR #136, consistent dialog sizes are specified by overriding [Material-UI's CSS API for Paper](https://material-ui.com/api/dialog/):
Specifically:
**paperWidthSm:** _Styles applied to the Paper component if maxWidth="sm"._
**paperWidthMd:** _Styles applied to the Paper component if maxWidth="md"._
**paperWidthLg:**  _Styles applied to the Paper component if maxWidth="lg"._
Small = maxWidth: 400px
Medium = maxWidth: 600px
Large = maxWidth: 800px
**No fixed height have been defined/ added to the override rules as of yet, it is currently defined by its content/material-ui component.**
The width are defined …
> set maxWidth on Dialogs for FileMenu and add Override rules for Material-UI Dialog  

- packages/org-unit-dialog/src/styles/OrgUnitSelector.style.js
- Some small style adjustments:
- Removed `width: 100%` for tooltip container element (previously user was unable to select org units under tooltip element.
- Transparent tooltip background (90%)
- Added `cursor: pointer` for selected org units labels.
- Bottom padding in org unit tree container (making room for tooltip)
> Fix styles in org units dialog component

- packages/core/package.json
- packages/period-selector-dialog/package.json
Problem: js changes in period-selector-dialog and core were not re-transpiled when running `yarn watch`.  This is because the --watch option gets applied at the end of the command. When you have a compound npm script (command1 && command2), then the option is applied to the last command.
It is actually possible to insert the option using shell functions aka:
```"npm run lint -- -f unix"```
```"lint": "f() { eslint -f src $@ . && npm run tslint; }; f"```
credit: https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script?lq=1
But this seemed unnecessarily complex for this one case. 
Downside is that css changes dont trigger the build.
> fix/re-order build script so --watch applies to babel transpiling

- packages/period-selector-dialog/package.json
- packages/period-selector-dialog/src/PeriodListItem.js
- packages/period-selector-dialog/src/Periods.js
- packages/period-selector-dialog/src/PeriodsList.js
- packages/period-selector-dialog/src/SelectedPeriods.js
- packages/period-selector-dialog/src/__tests__/PeriodListItem.spec.js
- yarn.lock
Enables user to drag and drop one selected item at a time to reorder. Multi-drag will be implemented in a follow-up PR
> feature/implement drag and drop to reorder selected periods in period-selector

- packages/period-selector-dialog/css/PeriodSelector.css
- packages/period-selector-dialog/src/FixedPeriods.js
- packages/period-selector-dialog/src/PeriodSelector.js
- packages/period-selector-dialog/src/Periods.js
- packages/period-selector-dialog/src/PeriodsList.js
- packages/period-selector-dialog/src/RelativePeriods.js
Fixes TECH-124.
- Filter periods that user is unselecting in order to keep offered periods list with correct options (TECH-124).
- Fix for deselect all click handler (previously it would just remove periods from selected list and not move them to offered one)
- Fix for reordering periods. Currently it only reorders periods within its own redux store.
Implementation for filtering periods on unselect (similar to approach used in data dimension):
On each periods generation create array of periods ids and keep it in component state.
Sync ids whenever user changes period type (from relative to fixed, or from weeks to months).
When user unselects periods, before putting them into offered list filter them (if period has its id in state) then it corresponds …
> Keep offered periods list populated with appropriate periods

- examples/create-react-app/src/components/rich-text.js
- packages/rich-text/README.md
- packages/rich-text/src/editor/Editor.js
- packages/rich-text/src/editor/__tests__/Editor.spec.js
- packages/rich-text/src/editor/__tests__/convertCtrlKey.spec.js
- packages/rich-text/src/editor/convertCtrlKey.js
- packages/rich-text/src/index.js
- packages/rich-text/src/parser/MdParser.js
- packages/rich-text/src/parser/Parser.js
- packages/rich-text/src/parser/__tests__/MdParser.spec.js
- packages/rich-text/src/parser/__tests__/Parser.spec.js
Separate the React components from the edit and parse functionality, to make it possible to use that functionality in non-react applications (e.g, "classic" analytics apps)
Most of the changes are just moving the editing and parsing functionality into separate files and making that accessible as exports from the package
> chore/separate edit and parse functionality from React

- examples/create-react-app/src/components/org-unit-dialog.js
- packages/org-unit-dialog/i18n/en.pot
- packages/org-unit-dialog/src/OrgUnitDialog.js
- packages/org-unit-dialog/src/OrgUnitSelector.js
- packages/org-unit-tree/src/OrgUnitTree.component.js
Fixes DHIS2-5495.
- Respect displayNameProperty prop for displaying org units/groups names
> Respect display name property in org units tree and options

- packages/org-unit-tree/src/OUCheckbox.component.js
- packages/org-unit-tree/src/OUFolderIcon.component.js
- packages/org-unit-tree/src/OrgUnitTree.component.js
- packages/org-unit-tree/src/styles/OUCheckbox.component.styles.js
- packages/org-unit-tree/src/styles/OrgUnitTree.component.styles.js
- packages/org-unit-tree/src/utils.js
Fixes DHIS2-5528.
* move styles to a separate file
* pull the loading function into a separate util.js file
* the render function has a bunch of comments that are unnecessary
* the render function has a high (poor) complexity score. Any way to simplify it? (e.g., make a OUCheckbox component, OUFolderIcon component), pull the event handlers out to standalone functions with argument...
> Refactor OrgUnitTree component

- examples/create-react-app/src/components/mentions-wrapper.js
- packages/mentions-wrapper/src/MentionsWrapper.js
- packages/mentions-wrapper/src/UserList.js
- packages/mentions-wrapper/src/__tests__/UserList.spec.js
This PR includes:
using ´lodash/sortBy` to sort available mentions by displayName.
Capital letters are prioritized, i checked the source code and it uses array.sort(), and MDN documentation states that:
```
The default sort order is built upon converting the elements into strings, then comparing their sequences of UTF-16 code units values.
```
This means that displayName with capital letters will be sorted first, and then displayNames without capital letters.
I confirmed this with concating the users with:
`
users.concat({id: 'testId', displayName: 'alain Traore', userCredentials: { username: 'traori' }})
`
I can change it to sort by `displayName.toLowerCase()`:
Additional info:
I've also updated the Typograhpy `variant` prop to use the new version as this was causing a warning.
* Test …
> Task/sort mentions list [DHIS2-5473]

- packages/rich-text/package.json
- packages/rich-text/src/editor/__tests__/convertCtrlKey.spec.js
- packages/rich-text/src/editor/convertCtrlKey.js
Undefined "this" was causing a javascript error and was obviously resulting in the rich text feature not working when using shortcut keys on a selected text. 
Unit test added. Also fixed the npm coverage script so that it has the needed configuration.
> Remove non-existent "this" from code

- packages/interpretations/src/models/interpretation.js
This PR contains small code refactoring in `packages/interpretations/src/models/Interpretation.js`
- Remove redundant async/await from delete/like methods
- Remove redundant .then(() => this)
- Return promise of the second request as a result in `save()` method
> Small refactor

- packages/rich-text/src/editor/__tests__/convertCtrlKey.spec.js
- packages/rich-text/src/editor/convertCtrlKey.js
Fixes [DHIS2-5773]
Call preventDefault() to stop the default action in firefox (ctrl+b opens bookmark panel, ctrl+i opens page info)
Note that the menu bar still briefly highlights the main menu item that would have been relevant.
> Rich-text editor: prevent default handler causing actions in Firefox

- examples/create-react-app/src/components/rich-text.js
- packages/rich-text/src/editor/__tests__/convertCtrlKey.spec.js
- packages/rich-text/src/editor/convertCtrlKey.js
Fixes [DHIS2-5819]
- when user select ctrl+b (or ctrl+i), then the double marker is added. The desired caret position is between the markers and is returned in the callback.
- when user selects text and then hits ctrl+b/i, then the text is wrapped in markers, and space added before/after the marker if there was none. The returned caret position is after the closing marker. Also, if leading/trailing spaces were part of the selection, they are trimmed.
See unit tests that describe expected behavior.
> Updates to rich-text editor to insert double markers, trim space and provide caret position

- packages/mentions-wrapper/src/MentionsWrapper.js
- packages/mentions-wrapper/src/UserList.js
- packages/mentions-wrapper/src/__tests__/UserList.spec.js
Related to DHIS2-5906.
The sorting of the user list cannot be done only when rendering the
component, the user list in the component's state must have the same
order, otherwise the arrow selection - which is using the state's user
list as index reference - is jumping around the list.
Opted for requesting an ordered list from the API instead, since the
render uses the same object stored in the state.
> Fix arrow handling in user list for mentions

- examples/create-react-app/package.json
- examples/create-react-app/src/components/period-picker.js
- packages/core/package.json
- packages/core/src/period-picker/PeriodPicker.component.js
- yarn.lock
Fixes DHIS2-5938.
**Changes proposed in this pull request:**
1. Add support for BiWeekly periods
2. Call `handleChange` when `this.props.periodType` changes, because the `this.props.onPickPeriod` callback might need to be triggered (i.e. when changing from _Monthly_ to _Yearly_)
3. Remove empty `MenuItem` from the `SelectField`. I can't imagine any scenario in which this would be useful
**Note:**
This PR depends on BiWeekly support in the d2 period parser which has not been merged into master yet at the time of writing. See https://github.com/dhis2/d2/pull/189
> Dhis2 5938 periodpicker support for biweekly and periodtype change

- packages/interpretations/src/components/Buttons/ActionButton.js
- packages/interpretations/src/components/Buttons/styles/ActionButton.style.js
- packages/interpretations/src/components/Interpretation/Likes.js
- packages/interpretations/src/components/Interpretation/Replies.js
- packages/interpretations/src/components/Interpretation/styles/LikesAndReplies.style.js
Maps Interpretation panel uses zIndex 1190,
tooltips have assigned zIndex 1200 in order to be rendered on top of the panel.
> add zIndex for interpretation button tooltips

- package.json
- packages/core/package.json
- packages/expression-manager/package.json
- packages/favorites-dialog/package.json
- packages/file-menu/package.json
- packages/forms/package.json
- packages/formula-editor/package.json
- packages/group-editor/package.json
- packages/header-bar/package.json
- packages/icon-picker/package.json
- packages/interpretations/i18n/en.pot
- packages/interpretations/package.json
- packages/legend/package.json
- packages/mentions-wrapper/package.json
- packages/org-unit-dialog/package.json
- packages/org-unit-select/package.json
- packages/org-unit-tree/package.json
- packages/period-selector-dialog/package.json
- packages/rich-text/package.json
- packages/sharing-dialog/package.json
- packages/table/package.json
- packages/translation-dialog/package.json
Fixes Jest runtime issues.
- Let the root `package.json` build specify the the `BABEL_ENV`, which determines if a `commonjs` or `es` build is being produced
- The packages themselves don't specify a `BABEL_ENV` in their build step, but "inherit" this from the root
> Build commonjs

- packages/interpretations/src/components/Avatar/styles/Avatar.style.js
add overflow:hidden to interpretations inner div, to keep content inside the grey div in maps app.
> patch: add overflow hidden to avatarBoxContent div

- src/legend/ColorPicker.component.js
Fixes: https://jira.dhis2.org/browse/DHIS2-5861
Related: https://github.com/dhis2/maintenance-app/pull/633
For the reviewers, I don't like the arbitrary z-index. However, there's no central area where all the z-indexes are defined. Or I couldn't find it at least. Maybe that'd be a good thing to tackle in a separate issue eventually.
The aria roles and tabindexes are mainly to satisfy eslint. A proper, accessible way to design this interface would be to not use divs as buttons in my opinion. Because even though they're focusable and tabbable now, they don't respond to keypresses, so it's still not accessible or very semantic.
I also removed the `is="popover"` attribute from the wrapping div (introduced in [this commit](https://github.com/dhis2/d2-ui/commit/ae13030601334d96787c3f2dc4b16741e4 …
> DHIS2-5861 - Fix colorpicker display bug

- packages/sharing-dialog/src/PermissionPicker.component.js
Relates to [DHIS2-6359](https://jira.dhis2.org/browse/DHIS2-6359)
- Use material-ui `MenuList` in `Sharing` component to apply correct paddings for access options list
Before fix:
After fix:
> fix: use MenuList material ui component to apply proper paddings in sharing/access dialog options

- src/legend/LegendItems.component.js
Fixes https://jira.dhis2.org/browse/DHIS2-6354 and addresses a point in https://jira.dhis2.org/browse/DHIS2-6365
> Fix legend item sorting v29

- packages/rich-text/src/parser/Parser.js
- packages/rich-text/src/parser/__tests__/Parser.spec.js
This PR includes validating that the passed children is not undefined/null before invoking the render method.
Passing undefined / null to the parser causes the app to crash.
> fix: rich-text parser, validate children before render

- packages/core/src/theme/mui3.theme.js
Fixes https://jira.dhis2.org/browse/DHIS2-6616 and https://jira.dhis2.org/browse/DHIS2-6654
- Set Menu prop "disableAutoFocusItem" to true by default, ref https://material-ui.com/api/menu
> fix: set menu prop disableAutoFocusItem to true by default

- packages/sharing-dialog/src/Sharing.component.js
- packages/sharing-dialog/src/SharingDialog.component.js
- packages/sharing-dialog/src/__tests__/SharingDialog.component.spec.js
This PR Includes removal of the apply button in `<SharingDialog>` when prop doNotPost is true.
Fix for [DHIS-6250](https://jira.dhis2.org/browse/DHIS2-6250)
Instead of calling prop `onConfirm` through the apply button, it is invoked through `closeDialog()` fn (added conditional check).
Additionally, the prop for typography have been updated to remove the warning.
Test cases have been adjusted.
> fix: remove apply button sharingdialog [DHIS2-6250]

- packages/interpretations/src/components/Comment/NewCommentField.js
- packages/interpretations/src/components/Interpretation/NewInterpretationField.js
This PR includes passing the caret pos and setting the node's selection range after pressing the hotkey `Ctrl + b` or `Ctrl + i`.
With this fix the caret pos will be placed in between the rich text symbols.
> fix: interpretation input field, caretPos for rich-text hotkeys

- packages/org-unit-tree/src/utils.js
In the new capture app, we are using the org unit tree from d2-ui. When expanding an org unit in the tree, and selecting a child, the child's org unit code is not included. We need this code to process program rules. 
- Include org unit code when loading org unit children
> Include org unit code when loading org unit children

- packages/rich-text/src/parser/MdParser.js
Not all browsers support lookbehind yet, only lookahead.
Replace the lookbehind with a non-capturing group match.
Explanation of regexp here: https://regex101.com/r/evswdV/1
> fix(rich-text): fix regexp in parser

- packages/core/src/action/Action.js
- packages/core/src/layout/SinglePanel.component.js
- packages/core/src/layout/TwoPanel.component.js
- packages/interpretations/package.json
- packages/interpretations/src/api/__tests__/helpers.spec.js
- packages/interpretations/src/api/users.js
- packages/interpretations/src/components/Cards/__tests__/InterpretationsCard.spec.js
- packages/interpretations/src/components/Interpretation/__tests__/Interpretation.spec.js
- packages/interpretations/src/components/Lists/__tests__/CommentsList.spec.js
- packages/interpretations/src/models/interpretation.js
- packages/org-unit-select/package.json
- packages/org-unit-tree/package.json
- packages/period-selector-dialog/package.json
- packages/translation-dialog/package.json
* Removing unused dependencies that were probably carried over when d2-ui was split into multiple packages
* use import syntax for lodash that ensures treeshaking
> chore: remove unused deps and fix lodash imports for treeshaking

- packages/period-selector-dialog/src/modules/FixedPeriodsGenerator.js
- packages/period-selector-dialog/src/modules/__tests__/FixedPeriodsGenerator.spec.js
This PR includes Epidemiological weeks for the Period Selector, related to ticket no. [6983](https://jira.dhis2.org/browse/DHIS2-6983).
1 new function `EpiWeeklyPeriodType` have been added.
The code is extracted and modified from the scripts available through [dhis-web-commons](https://play.dhis2.org/2.31.3/dhis-web-commons/javascripts/dhis2/dhis2.period.js?_=1561546342706).
Extracted fns:
```
dhis2.period.WeeklyWednesdayGenerator
dhis2.period.WeeklyThursdayGenerator
dhis2.period.WeeklySaturdayGenerator
dhis2.period.WeeklySundayGenerator
```
The previous `WeeklyPeriodType` generator have been modified to generate regular weekly intervals as well as epi-weeks.
> feat: add epi weeks to period selector dialog [DHIS2-6983]

- packages/rich-text/src/parser/MdParser.js
- packages/rich-text/src/parser/__tests__/MdParser.spec.js
Fixes DHIS2-7249.
- allow non-word character right after a bold or italic text, ie. ":"
> fix: fix rich text regexp to allow non-word characters after bold/italic

- packages/org-unit-dialog/src/OrgUnitSelector.js
- packages/org-unit-tree/src/OrgUnitTree.component.js
- packages/org-unit-tree/src/utils.js
Fixes DHIS2-7679.
- allow propagation of multiple ou roots from apps to `OrgUnitTreeMultipleRoots` used internally by `OrgUnitSelector`
> fix: support multiple ou roots in OrgUnitSelector component

- packages/interpretations/i18n/en.pot
- packages/interpretations/src/api/redirect.js
Fixes DHIS2-8118.
- visualization type needs to be supported in the interpretations component in order to show the AO's details and load the interpretations
> refactor: add support for visualization AO type

- package.json
- packages/interpretations/i18n/en.pot
- packages/interpretations/src/components/Comment/Comment.js
- packages/interpretations/src/components/Comment/__tests__/Comment.spec.js
- packages/interpretations/src/components/Lists/CommentsList.js
- packages/interpretations/src/components/Lists/__tests__/CommentsList.spec.js
Fixes DHIS2-8118.
- fix the interpretation comment delete
Before it was always deleting the last added comment, regardless of
which delete button was clicked.
Fixed by moving the DeleteDialog in the comments list component, we only
need one dialog anyway.
The comment to delete is set in the state via callback when the Delete button
on a comment is used.
When the dialog is confirmed the comment to delete is retrieved from the
state.
> fix: fix interpretation comment delete

- package.json
- packages/file-menu/src/GetLinkDialog.js
Fixes DHIS2-8208.
- fix the "Open in app" URL for visualization type objects
> fix: fix "Open in app" URL for visualization objects

- packages/period-selector-dialog/package.json
- yarn.lock
Upgrade to the latest @dhis/analytics library. No new features or bug fixes. This is an attempt to resolve an issue in dashboards where a seemingly wrong version of ui-core is causing a showstopping error. It seems really unlikely that the version of ui-core in period-selector (via @dhis2/analytics) would be the cause, but keeping dependencies current is usually a good idea anyway, right? :)
> fix: upgrade dhis2/analytics in period-selector-dialog

- package.json
- packages/period-selector-dialog/package.json
- yarn.lock
Due to the circular dependency between d2-ui-period-selector-dialog and @dhis2/analytics, we have to upgrade twice.
> fix: upgrade analytics to 4.0.1

- package.json
- packages/core/package.json
- yarn.lock
This hopefully solves the broken build in dashboards app, which seems to
be related by multiple versions of rxjs and missing rxjs-compat which
causes some imports from rxjs to fail.
Fixes DHIS2-8299.
> chore: add rxjs dep to d2-ui-core

- src/data-table/data-value/valueRenderers.js
Relates to DHIS2-7698.
This change will handle `in_ID` locales correctly and transform them to `in-ID` in the `DataTable` component.
It's the only component using the `keyUiLocale` value from the user settings, if this is the cause for all the issues in DHIS-7698, this could potentially solve a lot of issues.
> fix(data table): transform indonesian locale underscore to dash

- package.json
- packages/org-unit-dialog/src/OrgUnitSelector.js
Fixes DHIS2-6562.
- rename label for selecting sub units
> fix: label for selecting sub units in tree DHIS2-6562

- packages/favorites-dialog/src/actions/index.js
When a (new) filter is applied, always show the first page of the list,
regardless of which page was shown before the filter was applied.
Fixes https://jira.dhis2.org/browse/DHIS2-8451.
- reset the pagination to the first page when a filter is added/removed
> fix: reset pagination when using filters (DHIS2-8451)

- docs/RELEASING.md
It is not allowed to push directly to master anymore. Updating the RELEASING doc accordingly.
> chore: update info for publishing

- package.json
- packages/favorites-dialog/i18n/en.pot
- packages/favorites-dialog/src/EnhancedTable.js
Fixes DHIS2-8638.
https://jira.dhis2.org/browse/DHIS2-8638
- mark the pagination labels without words to prevent translation
Before:
After:
> fix: translations for pagination labels in FavoritesDialog

- packages/favorites-dialog/i18n/en.pot
- packages/favorites-dialog/src/icons/StackedAreaIcon.js
- packages/favorites-dialog/src/visTypes.js
Fixes [DHIS2-9217](https://jira.dhis2.org/browse/DHIS2-9217).
- add support for filtering Stacked area visualizations in the Open dialog (favorites-dialog package)
> feat: support Stacked area vis type in open dialog (DHIS2-9217)

- packages/rich-text/src/parser/MdParser.js
- packages/rich-text/src/parser/__tests__/MdParser.spec.js
Fixes [DHIS2-9382](https://jira.dhis2.org/browse/DHIS2-9382).
- fix regexp for correctly detecting the closing italic/bold marker when is preceded by a non-word character.
Fixes the specific case reported in the ticket and any other string where a non-word character is the last character before the closing italic/bold marker.
> fix: correctly detect italic/bold marker after non-word char  (DHIS2-9382)

- package.json
- packages/favorites-dialog/src/Favorites.js
I'm not exactly sure what happened between 2.34 and 2.35.
My theory is that in 2.35 we removed MUI dep in DV and now the MUI version used in DV is the one defined as dep of d2-ui, which happen to be a more recent version of what we have in DV in 2.34.
The behaviour of `maxWidth` has probably changed in MUI (different CSS).
The problem is the Dialog width jumping when paginating.
By passing `fullWidth` together with `maxWidth`, the width is always stretched to `maxWidth`.
Changed `maxWidth` to `md` as `lg` looks way too large on wide screens.
If the `md` size does not fit in the screen, the whole Dialog is resized.
> fix: lock the Dialog width so it doesn't jump when paginating

- package.json
- packages/org-unit-dialog/src/GridControl.js
- packages/org-unit-dialog/src/OrgUnitSelector.js
Bumps the z-index of the right-click menu and the two select elements in the org-unit-dialog to be compatible with @dhis2/ui z-index ranges. When used within a @dhis2/ui `Modal` (z-index 3000) the z-index needs to be higher than the modal's, which is why 3100 is used.
-----------
> fix: org-unit-dialog z-index issue

- package.json
- packages/favorites-dialog/src/Favorites.js
Required by https://github.com/dhis2/analytics/pull/655.
The new FileMenu uses `@dhis2/ui` components.
Conditional rendering is used to open a Popover component, since it doesn't have a `open` prop that can be toggled.
The problem was that the FavoritesDialog need to be added to the DOM with the `open` and `refreshData` props already set to `true`.
The old `componentWillReceiveProps`, never triggered, because those
props don't change in that case, they are just set when the `FavoritesDialog`
component renders.
`componentDidMount` is executed after the component is rendered, so the
condition for `open` and `refreshData` is checked also when using the
component without toggling the `open` prop.
`componentDidUpdate` is executed when a prop changes, this is triggered
when using the old …
> fix: replace unsafe componentWillReceiveProps method

- package.json
I didn't realise 7.0.9 was already released when merging #657
> fix: bump version to v7.0.10

- packages/sharing-dialog/src/AutoComplete.component.js
- packages/sharing-dialog/src/SharingDialog.component.js
- packages/sharing-dialog/src/UserSearch.component.js
Fixes DHIS2-6801.
- adds scroll bar to sharing dialogue suggestions
- limits sharing dialogue suggestions to 10 results
- increases debounce time on search to .5 seconds
(this implements PEPFAR's requested changes as laid out in the JIRA issue's comments)
> fix: add scrollbar for sharing dialog search results and limit result size from api request [DHIS2 6801]

- package.json
- packages/interpretations/config/test-context.js
- packages/interpretations/src/components/InterpretationsComponent/InterpretationsComponent.js
Requires the patched `d2`.
Fixes [DHIS2-10625](https://jira.dhis2.org/browse/DHIS2-10625).
- pass `fields=id` to `getUserGroups()` to greatly reduce the response size
The default used otherwise is `fields=:all`.
The interpretations component only uses the group ids:
https://github.com/dhis2/d2-ui/blob/master/packages/interpretations/src/components/InterpretationsComponent/InterpretationsComponent.js#L47
> fix(interpretations): reduce user groups response size (DHIS2-10625)

- packages/sharing-dialog/src/SharingDialog.component.js
- packages/translation-dialog/src/TranslationDialog.component.js
Part of fix for <DHIS2-10143>.
Add option to use the mui theme provider directly in the Sharing and Translation dialogs so that the parent app does not need to do this. In some cases the app will no longer need to have material-ui as a direct dependency (i.e., dashboard-app). Related PR:  https://github.com/dhis2/dashboard-app/pull/1704/)
Although it doesn't seem to matter if the theme is provided at multiple points (i.e., both at the app level and the component level), I added an option to avoid any potential errors I might not have found.
To test, remove the mui theme from the cra App.js, and change the insertTheme property in sharing.js and translation.js
> fix: add theme provider to translation and sharing dialogs [DHIS2-10143]

- package.json
- packages/favorites-dialog/package.json
- packages/favorites-dialog/src/Favorites.js
- packages/favorites-dialog/src/FavoritesDialog.js
- packages/file-menu/src/FileMenu.js
- packages/file-menu/src/OpenMenuItem.js
- packages/file-menu/src/ShareMenuItem.js
- packages/file-menu/src/TranslateMenuItem.js
- packages/interpretations/src/components/InterpretationsComponent/InterpretationsComponent.js
Fixes narrow dialogs issue related to [DHIS2-10143](https://jira.dhis2.org/browse/DHIS2-10143) .
- fix the narrow dialog issue due to missing MUI theme
Other than TranslationsDialog and SharingDialog, other components need the same fix:
- FileMenu
- FavoritesDialog
- Interpretations
> fix: add and propagate insertTheme prop (DHIS2-10143)

- packages/interpretations/i18n/en.pot
- packages/interpretations/src/components/Cards/InterpretationsCard.js
- packages/interpretations/src/components/Cards/styles/InterpretationsCard.style.js
- packages/interpretations/src/components/DetailsPanel/Description.js
- packages/interpretations/src/components/DetailsPanel/Details.js
- packages/interpretations/src/components/DetailsPanel/styles/Details.style.js
- packages/interpretations/src/components/InterpretationsComponent/InterpretationsComponent.js
- packages/sharing-dialog/src/Sharing.component.js
- packages/sharing-dialog/src/SharingDialog.component.js
Part of fix for https://jira.dhis2.org/browse/DHIS2-10874
* Interpretations: When the containing app is offline, then the input areas of the Interpretation are covered with an overlay containing text "Not available offline". Also, the subscription bell (in the description area) is disabled and has a tooltip on hover.
* Sharing: Place an overlay over everything but the CLOSE button
I decided not to introduce dhis2/ui as a dependency and instead copied css from the dhis2/ui ComponentCover and Center components. The Mui Tooltip also has the dhis2/ui Tooltip styling.
Some html and css changes were needed to get the tooltip on the subscription bell to work correctly. (like switching from `float` to `flexbox`.
Before:
After:
Online: (notice that the …
> feat: disable parts of interpretations and sharing components when offline [DHIS2-10874]

- packages/interpretations/src/dateformats/dateformatter.js
`Intl` wants locale in BCP 47 format, ie. de-AT with hyphen, but the
locale string coming from the api uses `_` instead.
Fixes a crash when opening the interpretations panel when the user's locale is contains the extended country information.
> fix: make sure locales are recognised by Intl

- packages/translation-dialog/src/TranslationDialog.component.js
- packages/translation-dialog/src/TranslationForm.component.js
A new property `isOnline` is added so that the Save button in Translation Dialog can be disabled if connectivity is lost.
https://user-images.githubusercontent.com/6113918/130642664-e7bdd1fe-f77f-4131-a7ba-98b2269e976e.mov
> fix: disable save button in translation dlg if offline [DHIS2-10874

- packages/interpretations/src/components/Cards/CollapsibleCard.js
> fix: children prop-type in interpretations CollapsibleCard is type node

- packages/interpretations/src/components/InterpretationsComponent/InterpretationsComponent.js
Fixes [DHIS2-12617](https://jira.dhis2.org/browse/DHIS2-12617)
- fix bug when checking if a user belongs to a group
This bug prevented to verify that the user belongs to a group and thus had access to write
a new interpretation.
Before:
After:
> fix: show new interpretation form when user/group has access DHIS2-12617

- package.json
- packages/rich-text/src/parser/MdParser.js
Fixes [LIBS-317](https://dhis2.atlassian.net/browse/LIBS-317).
- enable `link` rule in MarkdownIT parser
This correctly parses markdown links in the format: `[link text](url)`.
This markup has been added in the new rich text editor in LL app (to be moved from there).
Before:
After:
> feat: enable link rule

- package.json
- packages/interpretations/i18n/en.pot
- packages/interpretations/src/components/DetailsPanel/Details.js
- add missing title for LL visualizations
Before:
After:
> fix(interpretations): add title for LL visualizations
